import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import { QueryClientProvider } from '@tanstack/react-query'
import { queryClient } from '@/services/queryClient'
import "./globals.css";
import 'tailwindcss/tailwind.css';

import { cn } from "@/lib/utils"
 
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <QueryClientProvider client={queryClient}>
      <html lang="en">
        <body className={cn(
            "min-h-screen bg-background font-sans antialiased",
            fontSans.variable
          )}>{children}</body>
      </html>
    </QueryClientProvider>
  );
}
